# 2.1 파이토치 개요

In [ ]:
import torch
torch.tensor([[1., -1.], [1., -1.]])

tensor([[ 1., -1.],
        [ 1., -1.]])

# 2.2 파이토치 기본 문법

## 2.2.1 텐서 다루기기

In [ ]:
import torch
print(torch.tensor([[1,2],[3,4]])) # 2차원 형태의 텐서 생성
print('----------------------------')
print(torch.tensor([[1,2],[3,4]], device="cuda:0")) # GPU에 텐서 생성
print('----------------------------')
print(torch.tensor([[1,2],[3,4]], dtype=torch.float64)) # dtype을 이용하여 텐서 생성

tensor([[1, 2],
        [3, 4]])
----------------------------
tensor([[1, 2],
        [3, 4]], device='cuda:0')
----------------------------
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [ ]:
temp = torch.tensor([[1,2], [3,4]])
print(temp.numpy()) # 텐서를 ndarray로 변환
print('----------------------------')
print(type(temp.numpy()))

[[1 2]
 [3 4]]
----------------------------
<class 'numpy.ndarray'>


In [ ]:
temp = torch.tensor([[1,2],[3,4]], device='cuda:0')
print(temp.to('cpu').numpy())

[[1 2]
 [3 4]]


In [ ]:
temp = torch.FloatTensor([1,2,3,4,5,6,7]) # 파이토치로 1차원 벡터 생성
print(temp[0], temp[1], temp[-1]) # 인덱스로 접근
print('----------------------------')
print(temp[2:5], temp[4:-1]) # 슬라이스로 접근

tensor(1.) tensor(2.) tensor(7.)
----------------------------
tensor([3., 4., 5.]) tensor([5., 6.])


In [ ]:
v = torch.tensor([1,2,3]) # 길이가 3인 벡터 생성
w = torch.tensor([3,4,6])
print(v - w) # 길이가 같은 벡터 간 뺼셈 연산

tensor([-2, -2, -3])


In [ ]:
temp = torch.tensor([[1,2],[3,4]]) # 2x2 행렬 생성
print(temp.shape)
print('----------------------------')
print(temp.view(4,1)) # 2x2 행렬을 4x1 행렬로 변형
print('----------------------------')
print(temp.view(-1)) # 2x2 행렬을 1차원 벡터로 변형
print('----------------------------')
print(temp.view(1,-1)) # -1은 (1, ?)와 같은 의미로 다른 차원으로부터 해당 값을 유추하겠다는 의미
print('----------------------------')
print(temp.view(-1,1)) # 2x2 행렬을 1x4 행렬로 변환

torch.Size([2, 2])
----------------------------
tensor([[1],
        [2],
        [3],
        [4]])
----------------------------
tensor([1, 2, 3, 4])
----------------------------
tensor([[1, 2, 3, 4]])
----------------------------
tensor([[1],
        [2],
        [3],
        [4]])


## 2.2.2 데이터 준비

In [ ]:
import pandas as pd
import torch
from torch.utils.data import Dataset
from torch.utils.data import DataLoader

class CustomDataset(Dataset):
    def __init__(self, csv_file): 
				# 필요한 변수를 선언하고, 데이터셋의 전처리를 해주는 함수
        self.label = pd.read_csv(csv_file)
    
    def __len__(self): # 데이터셋의 길이. 즉, 총 샘플의 수를 반환하는 함수
        return len(self.label)

    def __getitem__(self, index):
				sample = torch.tensor(self.label.iloc[idx,0:3]).int()
				label = torch.tensor(self.label.iloc[idx,3).int()
				return sample, label
        # 데이터셋에서 특정 데이터를 가져오는 함수
				# index번째 데이터를 반환하는 함수이며, 
				# 이때 반환되는 값은 텐서의 형태를 취해야 한다.

tensor_dataset = CustomDataset('.../example.csv') # 데이터셋으로 example.csv 사용

# 데이터셋을 DataLoader에 파라미터로 전달
dataset = DataLoader(tensor_dataset, batch_size=4, shuffle=True) 

In [ ]:
import torchvision.transforms as transforms

mnist_transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (1.0,))
]) # 평균이 0.5, 표준편차가 1.0이 되도록 데이터의 분포를 조정

from torchvision.datasets import MNIST
import requests
download_root = '/content/sample_data' # 다운로드 경로 지정정

train_dataset = MNIST(download_root, transform=mnist_transform, train=True, download=True) # 훈련 데이터셋
valid_dataset = MNIST(download_root, transform=mnist_transform, train=False, download=True) # 검증 데이터셋
test_dataset = MNIST(download_root, transform=mnist_transform, train=False, download=True) # 테스트 데이터셋

  0%|          | 0/9912422 [00:00<?, ?it/s]

Extracting /content/sample_data/MNIST/raw/train-images-idx3-ubyte.gz to /content/sample_data/MNIST/raw



  0%|          | 0/28881 [00:00<?, ?it/s]

Extracting /content/sample_data/MNIST/raw/train-labels-idx1-ubyte.gz to /content/sample_data/MNIST/raw



  0%|          | 0/1648877 [00:00<?, ?it/s]

Extracting /content/sample_data/MNIST/raw/t10k-images-idx3-ubyte.gz to /content/sample_data/MNIST/raw



  0%|          | 0/4542 [00:00<?, ?it/s]

Extracting /content/sample_data/MNIST/raw/t10k-labels-idx1-ubyte.gz to /content/sample_data/MNIST/raw



## 2.2.3 모델 정의

In [ ]:
import torch.nn as nn
model = nn.Linear(in_features=1, out_features=1, bias=True)

In [ ]:
from torch.nn import Module

class MLP(Module):
    def __init__(self, inputs): # 모델에서 사용되어야 할 모듈, 활성화 함수 등을 정의
        super(MLP, self).__init__()
        self.layer = Linear(inputs, 1) # 계층 정의
        self.activation = Sigmoid() # 활성화 함수 정의

    def forward(self, X): # 모델에서 실행되어야 할 연산을 정의
        X = self.layer(X)
        X = self.activation(X)
        return x

In [ ]:
import torch.nn as nn

class MLP(nn.Module):
    def __init__(self):
        super(MLP, self).__init__()
        self.layer1 = nn.Sequential(
            nn.Conv2d(in_channels=3, out_channels=64, kernel_size=5),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2)
        )

        self.layer2 = nn.Sequential(
            nn.Conv2d(in_channels=64, out_channels=3, kernel_size=5),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2)
        )

        self.layer3 = nn.Sequential(
            nn.Linear(in_features=30*5*5, out_features=10, bias=True),
            nn.ReLU(inplace=True)
        )

    def forward(self, x):
        x = self.layer1(x)
        x = self.layer2(x)
        x = x.view(x.shape[0], -1)
        x = self.layer3(x)
        return x

model = MLP() # 모델에 대한 객체 생성성

print('Printing children\n---------------------------------')
print(list(model.children()))
print('\n\nPrinting Modules\n--------------------------------')
print(list(model.modules()))

Printing children
---------------------------------
[Sequential(
  (0): Conv2d(3, 64, kernel_size=(5, 5), stride=(1, 1))
  (1): ReLU(inplace=True)
  (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
), Sequential(
  (0): Conv2d(64, 3, kernel_size=(5, 5), stride=(1, 1))
  (1): ReLU(inplace=True)
  (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
), Sequential(
  (0): Linear(in_features=750, out_features=10, bias=True)
  (1): ReLU(inplace=True)
)]


Printing Modules
--------------------------------
[MLP(
  (layer1): Sequential(
    (0): Conv2d(3, 64, kernel_size=(5, 5), stride=(1, 1))
    (1): ReLU(inplace=True)
    (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer2): Sequential(
    (0): Conv2d(64, 3, kernel_size=(5, 5), stride=(1, 1))
    (1): ReLU(inplace=True)
    (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer3): Sequential(
    (0): Li

In [ ]:
def MLP(in_features=1, hidden_features=20, out_features=1):
    hidden = nn.Linear(in_features=in_features, out_features=out_features, bias=True)
    activation = nn.ReLU()
    output = nn.Linear(in_features=hidden_features, out_features=out_features, bias=True)
    net = nn.Sequential(hidden, activation, output)
    return set

In [ ]:
from torch.optim import optimizer

criterion = torch.nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01, momentum=0.9)
scheduler = torch.optim.lr_scheduler.LambdaLR(optimizer=optimizer, lr_lambda=lambda epoch:0.95**epoch)

for epoch in range(1, 100+1): # epoch 수만큼 데이터를 반복하여 처리
    for x,y in dataloader: # 배치 크기만큼 데이터를 가져와서 학습 진행
        optimizer.zero_grad()

loss_fn(model(x), y).backward()
optimizer.step()
scheduler.step()

In [ ]:
for epoch in range(100):
    yhat = model(x_train)
    loss = criterion(yhat, y_train)
    optimizer.zero_grad() # 오차가 중첩적으로 쌓이지 않게 초기화
    loss.backward()
    optimizer.step()

In [ ]:
import torch
import torchmetrics

preds = torch.randn(10,5).softmax(dim=-1)
target = torch.randint(5, (10,))

acc = torchmetrics.functional.accuracy(preds, target)

In [ ]:
import torch
import torchmetrics

metric = torchmetrics.Accuracy()

n_batches = 10
for i range(n_batches):
    preds = torch.randn(10,5).softmax(dim=-1)
    target = torch.randint(5, (10,))

    acc = metric(preds, target)
    print(f"Accuracy on batch {i} : {acc}") # 현재 배치에서 모델 평가(정확도)
    
acc = metric.compute()
print(f"Accuracy on all data : {acc}") # 모든 배치에서 모델 평가(정확도도)

In [ ]:
import torch
from torch.utils.tensorboard import SummaryWriter

writer = SummaryWriter('.../content/sample') # 모니터링에 필요한 값들이 저장될 위치

for epoch in range(num_epochs):
    model.train() # 학습 모드로 전환(dropout=True)
    batch_loss = 0.0

for i, (x,y) in enumerate(dataloader):
    x,y = x.to(device).float(), y.to(device).float()
    outputs = model(x)
    loss = criterion(outputs,y)
    writer.add_scalar("Loss", loss, epoch) # 스칼라 값을 기록
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

writer.close() # summarywriter가 더 이상 필요하지 않으면 close() 메서드를 호출

In [ ]:
model.eval() # 검증 모드로 전환 (dropout=False)
with torch.no_grad():
    valid_loss = 0

    for x,y in valid_dataloader:
        outputs = model(x)
        loss = F.cross_entropy(outputs, y.long().squeeze())
        valid_loss += float(loss)
        y_hat += [outputs]

    valid_loss = valid_loss / len(valid_loss)